Repository nsnnsn12/pr2s, pull requests merged in 2022-07, with the labels that each got.

#30 feat : 기본 Repository 생성 #24 해결
  src/main/java/com/metacrew/pr2s/repository/AddressRepository.java
  src/main/java/com/metacrew/pr2s/repository/ArticleRepository.java
  src/main/java/com/metacrew/pr2s/repository/BoardRepository.java
  src/main/java/com/metacrew/pr2s/repository/BookmarkRepository.java
  src/main/java/com/metacrew/pr2s/repository/CommentRepository.java
  src/main/java/com/metacrew/pr2s/repository/CommonCodeKindRepository.java
  src/main/java/com/metacrew/pr2s/repository/CommonCodeRepository.java
  src/main/java/com/metacrew/pr2s/repository/FileRepository.java
  src/main/java/com/metacrew/pr2s/repository/InstitutionRepository.java
  src/main/java/com/metacrew/pr2s/repository/JoinInfoRepository.java
  src/main/java/com/metacrew/pr2s/repository/ManagerRepository.java
  src/main/java/com/metacrew/pr2s/repository/MemberRepository.java
  src/main/java/com/metacrew/pr2s/repository/ReservationRepository.java
  src/main/java/com/metacrew/pr2s/repository/RoomImageRepository.java
  src/main/java/com/metacrew/pr2s/repository/RoomRepository.java
Labels: feature

#43 Feature/41
  src/main/java/com/metacrew/pr2s/dto/JoinMemberDto.java
  src/main/java/com/metacrew/pr2s/entity/Member.java
  src/main/java/com/metacrew/pr2s/repository/JoinInfoRepository.java
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberTestService.java
  src/test/java/com/metacrew/pr2s/entity/MemberTest.java
  src/test/java/com/metacrew/pr2s/repository/JoinInfoRepositoryTest.java
  src/test/java/com/metacrew/pr2s/service/memberservice/MemberTestServiceTest.java
Labels: feature

#46 Feature/44
  src/main/java/com/metacrew/pr2s/dto/MyPageDto.java
  src/main/java/com/metacrew/pr2s/entity/Member.java
  src/main/java/com/metacrew/pr2s/repository/joinforepository/JoinInfoRepository.java
  src/main/java/com/metacrew/pr2s/repository/memberrepository/MemberRepository.java
  src/main/java/com/metacrew/pr2s/service/memberservice/ClientMemberService.java
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberService.java
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberTestService.java
  src/test/java/com/metacrew/pr2s/entity/JoinInfoTest.java
  src/test/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoRepositoryTest.java
  src/test/java/com/metacrew/pr2s/repository/memberrepository/MemberRepositoryTest.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
  src/test/java/com/metacrew/pr2s/service/memberservice/MemberTestServiceTest.java
Labels: feature

#54 Feat/53
  src/main/java/com/metacrew/pr2s/entity/File.java
  src/test/java/com/metacrew/pr2s/entity/FileTest.java
Labels: feature

#55 Feat/51
  src/main/java/com/metacrew/pr2s/repository/memberrepository/MemberTestRepository.java
  src/main/java/com/metacrew/pr2s/service/memberservice/ClientMemberService.java
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberService.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
Labels: refactoring

#57 Feat : ClientMemberServiceTest 회원가입시 프로필을 등록하는 경우 테스트
  src/main/java/com/metacrew/pr2s/entity/File.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
Labels: feature

#58 DOCS : MemberService join 주석 수정
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberService.java
Labels: feature

#62 feat/59 MemberService 주석 수정
  src/main/java/com/metacrew/pr2s/service/memberservice/ClientMemberService.java
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberService.java
Labels: documentation

#72 Feat/63
  src/main/java/com/metacrew/pr2s/service/memberservice/ClientMemberService.java
  src/main/java/com/metacrew/pr2s/service/memberservice/MemberService.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
Labels: feature

#61 REFACTOR : 기관 수정 기능 예외 처리 추가 및 필수 파라미터 반영
  src/main/java/com/metacrew/pr2s/dto/InstitutionCreateDto.java
  src/main/java/com/metacrew/pr2s/entity/Address.java
  src/main/java/com/metacrew/pr2s/entity/Institution.java
  src/main/java/com/metacrew/pr2s/entity/Workdays.java
  src/main/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerService.java
  src/main/java/com/metacrew/pr2s/service/institutionservice/InstitutionService.java
  src/test/java/com/metacrew/pr2s/entity/InstitutionTest.java
  src/test/java/com/metacrew/pr2s/entity/JoinInfoTest.java
  src/test/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoRepositoryTest.java
  src/test/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerServiceTest.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
Labels: refactoring

#75 FEAT : TimePeriod 임베디드 타입 생성 및 Period 타입 이름 변경
  src/main/java/com/metacrew/pr2s/dto/InstitutionCreateDto.java
  src/main/java/com/metacrew/pr2s/entity/Institution.java
  src/main/java/com/metacrew/pr2s/entity/Reservation.java
  src/main/java/com/metacrew/pr2s/entity/embedded/DatePeriod.java
  src/main/java/com/metacrew/pr2s/entity/embedded/TimePeriod.java
Labels: feature

#78 Feature/73
  src/main/java/com/metacrew/pr2s/dto/condition/JoinInfoConditionDto.java
  src/main/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoQueryRepository.java
  src/main/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoQueryRepositoryImpl.java
  src/main/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoRepository.java
  src/main/java/com/metacrew/pr2s/service/institutionmemberservice/InstitutionMemberManagerService.java
  src/main/java/com/metacrew/pr2s/service/institutionmemberservice/InstitutionMemberService.java
  src/main/java/com/metacrew/pr2s/service/memberservice/ClientMemberService.java
  src/test/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoQueryRepositoryImplTest.java
  src/test/java/com/metacrew/pr2s/repository/joininforepository/JoinInfoRepositoryTest.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
Labels: feature

#65 REFACTOR : RoomService registerRoom 방 등록 기능 리팩토링
  src/main/java/com/metacrew/pr2s/dto/RoomDto.java
  src/main/java/com/metacrew/pr2s/entity/Room.java
  src/main/java/com/metacrew/pr2s/repository/RoomRepository.java
  src/main/java/com/metacrew/pr2s/repository/roomrepository/RoomRepository.java
  src/main/java/com/metacrew/pr2s/repository/roomrepository/RoomTestRepository.java
  src/main/java/com/metacrew/pr2s/service/roomservice/RoomManagerService.java
  src/main/java/com/metacrew/pr2s/service/roomservice/RoomService.java
  src/main/java/com/metacrew/pr2s/service/roomservice/RoomTestService.java
  src/test/java/com/metacrew/pr2s/entity/RoomTest.java
  src/test/java/com/metacrew/pr2s/repository/roomrepository/RoomTestRepositoryTest.java
  src/test/java/com/metacrew/pr2s/service/roomservice/RoomManagerServiceTest.java
  src/test/java/com/metacrew/pr2s/service/roomservice/RoomTestServiceTest.java
Labels: refactoring

#79 REFACTOR : 기관 엔터티 TimePeriod 추가 후 기관 수정 테스트 수정
  src/main/java/com/metacrew/pr2s/dto/InstitutionCreateDto.java
  src/main/java/com/metacrew/pr2s/dto/WorkdaysDto.java
  src/main/java/com/metacrew/pr2s/entity/Institution.java
  src/main/java/com/metacrew/pr2s/entity/embedded/TimePeriod.java
  src/test/java/com/metacrew/pr2s/entity/embedded/TimePeriodTest.java
  src/test/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerServiceTest.java
Labels: refactoring

#83 Feature/76
  src/main/java/com/metacrew/pr2s/Pr2sApplication.java
  src/main/java/com/metacrew/pr2s/TestDataLoader.java
  src/main/java/com/metacrew/pr2s/entity/JoinInfo.java
  src/main/java/com/metacrew/pr2s/entity/enums/FileType.java
  src/test/java/com/metacrew/pr2s/service/memberservice/ClientMemberServiceTest.java
Labels: feature
